"""Execution layer for Agent OS — project-scoped Coding Agent workspaces."""

from .models import (
    ExecutionWorkspace,
    TaskSpec,
    RunRecord,
    RunStatus,
    ResultSummary,
)
from .manager import (
    get_execution_root,
    get_project_execution_dir,
    init_execution_workspace,
    get_execution_workspace,
    read_task_state,
    update_task_state,
)
from .sandbox import ProjectSandbox, SandboxViolation
from .tool_models import ToolResult
from .tool_runtime import ToolRuntime
from .runner import CodingAgentRunner
from .background import (
    BackgroundRunManager,
    get_default_manager,
    shutdown_default_manager,
)
from .chat_delegation import (
    is_code_delegation,
    handle_code_delegation,
    GENERAL_REJECTION_MESSAGE,
)
from .delegation_intent import (
    looks_like_code_request,
    derive_task_card,
    render_suggestion,
)
from .delegation_judge import (
    DelegationDecision,
    judge_delegation,
    render_dispatch_suggestion,
    DECISION_DISPATCH,
    DECISION_DISCUSSION,
    DECISION_MEMORY_ONLY,
)
from .pending_execution import (
    PendingExecutionView,
    PlanRevision,
    serialize_pending,
    revise_pending_plan,
    render_pending_chat_body,
    render_revised_chat_body,
    derive_title_from_card,
    STATUS_PENDING,
    STATUS_DISPATCHED,
    STATUS_CANCELLED,
)
from .memory_reconciliation import (
    ReconciliationDecision,
    ReconciliationOutcome,
    ReconciliationUpdate,
    RECONCILIATION_WRITABLE_FILES,
    judge_run_memory_reconciliation,
    reconcile_run_memory,
    TAG_APPLIED,
    TAG_ERROR,
    TAG_SKIPPED_ALREADY_RECONCILED,
    TAG_SKIPPED_FAILED_NOISY,
    TAG_SKIPPED_JUDGE_NO_UPDATE,
    TAG_SKIPPED_NO_VALID_UPDATES,
    TAG_SKIPPED_NON_TERMINAL,
    TAG_SKIPPED_READ_ONLY,
)
from . import preview
from .preview import (
    PreviewServer,
    adopt_preview,
    get_preview_status,
    shutdown_all_previews,
    start_preview,
    stop_preview,
)
from .inspect import (
    InspectionResult,
    INSPECT_MAX_LIST_ENTRIES,
    INSPECT_MAX_READ_CHARS,
    INSPECT_MAX_SEARCH_HITS,
    execute_inspect_request,
    format_result_for_llm,
    inspect_system_prompt_section,
    list_repo_files,
    parse_inspect_request,
    read_repo_file,
    search_repo_files,
)

__all__ = [
    "ExecutionWorkspace",
    "TaskSpec",
    "RunRecord",
    "RunStatus",
    "ResultSummary",
    "get_execution_root",
    "get_project_execution_dir",
    "init_execution_workspace",
    "get_execution_workspace",
    "read_task_state",
    "update_task_state",
    "ProjectSandbox",
    "SandboxViolation",
    "ToolResult",
    "ToolRuntime",
    "CodingAgentRunner",
    "BackgroundRunManager",
    "get_default_manager",
    "shutdown_default_manager",
    "is_code_delegation",
    "handle_code_delegation",
    "GENERAL_REJECTION_MESSAGE",
    "looks_like_code_request",
    "derive_task_card",
    "render_suggestion",
    "DelegationDecision",
    "judge_delegation",
    "render_dispatch_suggestion",
    "DECISION_DISPATCH",
    "DECISION_DISCUSSION",
    "DECISION_MEMORY_ONLY",
    "PendingExecutionView",
    "PlanRevision",
    "serialize_pending",
    "revise_pending_plan",
    "render_pending_chat_body",
    "render_revised_chat_body",
    "derive_title_from_card",
    "STATUS_PENDING",
    "STATUS_DISPATCHED",
    "STATUS_CANCELLED",
    "ReconciliationDecision",
    "ReconciliationOutcome",
    "ReconciliationUpdate",
    "RECONCILIATION_WRITABLE_FILES",
    "judge_run_memory_reconciliation",
    "reconcile_run_memory",
    "TAG_APPLIED",
    "TAG_ERROR",
    "TAG_SKIPPED_ALREADY_RECONCILED",
    "TAG_SKIPPED_FAILED_NOISY",
    "TAG_SKIPPED_JUDGE_NO_UPDATE",
    "TAG_SKIPPED_NO_VALID_UPDATES",
    "TAG_SKIPPED_NON_TERMINAL",
    "TAG_SKIPPED_READ_ONLY",
    "preview",
    "PreviewServer",
    "adopt_preview",
    "get_preview_status",
    "shutdown_all_previews",
    "start_preview",
    "stop_preview",
    "InspectionResult",
    "INSPECT_MAX_LIST_ENTRIES",
    "INSPECT_MAX_READ_CHARS",
    "INSPECT_MAX_SEARCH_HITS",
    "execute_inspect_request",
    "format_result_for_llm",
    "inspect_system_prompt_section",
    "list_repo_files",
    "parse_inspect_request",
    "read_repo_file",
    "search_repo_files",
]
